# Setting Server Port
server:
    port: 19002

# Setting Logging Config
logging:
    config: classpath:log4j2-spring.xml

# Setting EAI
EAI:
    xml-encoding: EUC-KR
    check-file-path: ./.xxx.t
    call-timeout-millis: 60000

# Setting Spring
spring:
    profiles:
        active: local
    application:
        name: hans-admin

# Setting DB Connection
    oracle:
        datasource:
            driver-class-name: oracle.jdbc.driver.OracleDriver
            jdbc-url: jdbc:oracle:thin:@ipAddress:1521:접속ID
            username: 접속ID
            password: 비밀번호

    mssql:
        datasource:
            driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
            jdbc-url: jdbc:sqlserver://ipAddress:1433;databaseName=이름;
            username: 접속ID
            password: "비밀번호"

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

    messages:
        basename: classpath:/messages/message
        encoding: UTF-8
        cache-duration:
            seconds: -1
    main:
    # userDetailService
    # 스프링 제공 함수 안쓰고 정의한 함수로 바꾸기 위한 설정
        allow-bean-definition-overriding: true
    redis:
        lettuce:
            pool:
                max-active: 10
                max-idle: 10
                min-idle: 2
        host: redis ipAddress
        port: redis portNumber